name: Build

on:
  push:

jobs:
  php:
    runs-on: ubuntu-latest
    name: PHP
    strategy:
      matrix:
        php-version: [8.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: Install Composer dependencies
        run: composer install
        working-directory: app

  node:
    needs: php
    runs-on: ubuntu-latest
    name: Node.js
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Create vendor directory
        run: composer install
        working-directory: app
      - uses: actions/checkout@v3
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Node dependencies
        run: yarn install
        working-directory: app
