name: push.yml

on:
  push:
    branches:
      - 'develop'
      - 'feature/**'
      - '!release'
      - '!main'

jobs:
  print-event:
    runs-on: ubuntu-latest

    steps:
      - name: Push event that triggered this workflow
        run: |
          echo $("Push events on branch dev with excluding staging and including branch who start with feature/")